config/routes.rb
Chirp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'

  match '/help', to: 'static_pages#help'

  match '/about', to: 'static_pages#about'

  match '/contact', to: 'static_pages#contact'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/views/shared/_delete_link.html.slim
= link_to "delete", object, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: object.content

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_explanation
    .alert.alert-error
      The form contains #{pluralize(object.errors.count, 'error')}.
    ul
      - object.errors.full_messages.each do |msg|
        li= msg

app/views/shared/_feed.html.slim
- if @feed_items.any?
  ol.microposts
    = render partial: 'shared/feed_item', collection: @feed_items
  = will_paginate @feed_items

app/views/shared/_feed_item.html.slim
li id="#{feed_item.id}"
  = link_to gravatar_for(feed_item.user), feed_item.user
  span.user
    = link_to feed_item.user.name, feed_item.user
  span.content
    = wrap(feed_item.content)
  span.timestamp>
    Posted #{time_ago_in_words(feed_item.created_at)} ago.
  - if current_user?(feed_item.user)
    = render 'shared/delete_link', object: feed_item

app/views/shared/_micropost_form.html.slim
= form_for(@micropost) do |f|
  = render 'shared/error_messages', object: f.object
  .field
    = f.text_area :content, placeholder: "Compose new micropost..."
  = f.submit "Post", class: "btn btn-large btn-primary"

app/views/shared/_stats.html.slim
- @user ||= current_user
.stats
  a<> href="#{following_user_path(@user)}"
    strong#following.stat
      = @user.followed_users.count
    | following
  a<> href="#{followers_user_path(@user)}"
    strong#followers.stat
      = @user.followers.count
    | followers

app/views/shared/_user_info.html.slim
= link_to user_path(current_user) do
  = gravatar_for current_user, size: 52
h1
  = current_user.name
span
  = link_to "view my profile", current_user
span
  = pluralize(current_user.microposts.count, "micropost")