config/routes.rb
Chirp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'

  match '/help', to: 'static_pages#help'

  match '/about', to: 'static_pages#about'

  match '/contact', to: 'static_pages#contact'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/views/layouts/_footer.html.slim
footer.footer
  small
    a href='http://railstutorial.org/' Rails Tutorial by Michael Hartl
  nav
    ul
      li= link_to 'About', about_path
      li= link_to 'Contact', contact_path
      li: a href='http://news.railstutorial.org/' News

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to 'sample app', root_path, id: 'logo'
      nav
        ul.nav.pull-right
          li= link_to 'Home', root_path
          li= link_to 'Help', help_path
          - if signed_in?
            li= link_to "Users", users_path
            li.dropdown#fat-menu
              = link_to '#', class: 'dropdown-toogle', data: {toggle: 'dropdown'} do
                = 'Account'
                b.caret
              ul.dropdown-menu
                li= link_to 'Profile', current_user
                li= link_to 'Settings', edit_user_path(current_user)
                li.divider
                li= link_to 'Sign out', signout_path, method: 'delete'
          - else
            li= link_to 'Sign in', signin_path

app/views/layouts/_shim.html.slim
/[if lt IE 9]
  script src='http://html5shiv.googlecode.com/svn/trunk/html5.js'

app/views/layouts/application.html.slim
doctype html
html
  head
    title= full_title(yield(:title))
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
    = render 'layouts/shim'

  body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        div class="alert alert-#{key}"
          = value
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?
    = javascript_include_tag 'application'